extends PanelContainer

# Act 1 headlines — innocent party host framing
const ACT1_HEADLINES: Array[String] = [
	"LOCAL PHILANTHROPIST HOSTS RECORD-BREAKING FUNDRAISER ON PRIVATE ISLAND",
	"EXCLUSIVE RESORT ATTRACTS HIGH-PROFILE GUESTS FROM ACROSS THE GLOBE",
	"ISLAND GETAWAY BECOMES HOT TICKET FOR ELITE NETWORKING EVENTS",
	"PRIVATE VENUE SEES SURGE IN BOOKINGS AS WORD SPREADS AMONG THE WELL-CONNECTED",
	"SOCIALITE CIRCLES BUZZ OVER MYSTERY HOST'S LEGENDARY HOSPITALITY",
	"FINANCIER'S ISLAND PARTIES DESCRIBED AS 'ONCE IN A LIFETIME' BY ATTENDEES",
	"OFFSHORE ACCOUNTS SHOW STRONG RETURNS AS RESORT EXPANSION CONTINUES",
	"GUEST LIST GROWS AS MORE PROMINENT FIGURES SEEK INVITATIONS",
	"ISLAND INFRASTRUCTURE INVESTMENT DRAWS PRAISE FROM REGIONAL ECONOMISTS",
	"PROMINENT POLITICAL FIGURE SPOTTED VACATIONING AT EXCLUSIVE ISLAND ESTATE",
	"LUXURY YACHT FLEET EXPANDED TO ACCOMMODATE GROWING VIP CLIENTELE",
	"PRIVATE JET ARRIVALS UP 300% — ISLAND HOST BECOMES SOUGHT-AFTER DESTINATION",
]

# Act 2 headlines — increasingly suspicious, implications of something darker
const ACT2_HEADLINES: Array[String] = [
	"SOURCES: ISLAND HOST REQUIRES SIGNED DISCRETION AGREEMENTS FROM ALL GUESTS",
	"UNDISCLOSED GUESTS ARRIVE UNDER COVER OF NIGHT AT REMOTE ISLAND COMPOUND",
	"FINANCIER'S PRIVATE ARRANGEMENTS DESCRIBED AS 'MUTUALLY BENEFICIAL' BY INSIDERS",
	"EXCLUSIVE CLIENTELE VETTED THROUGH UNNAMED INTERMEDIARIES, SOURCES SAY",
	"ISLAND OPERATION EXPANDS WITH ADDITIONAL STAFF SWORN TO CONFIDENTIALITY",
	"CERTAIN FAVORS EXCHANGED AT ELITE GATHERINGS, FORMER ATTENDEE CLAIMS",
	"HIGH-PROFILE VISITORS TRAVEL WITHOUT SECURITY DETAIL OR OFFICIAL RECORD",
	"DISCRETION IS OUR BUSINESS: ISLAND STAFF REPORTEDLY SIGN MULTI-DECADE NDAs",
	"FLIGHT LOGS SHOW UNNAMED PASSENGERS ABOARD PRIVATE AIRCRAFT — NO MANIFESTS FILED",
	"ISLAND COMPOUND REPORTEDLY OFF-LIMITS TO LOCAL AUTHORITIES WITHOUT INVITATION",
]

# Ghost Mode Act 1 headlines — sinister from the start
const ACT1_GHOST_HEADLINES: Array[String] = [
	"SOURCES: MYSTERIOUS NEW OPERATION QUIETLY REOPENED ON PRIVATE ISLAND",
	"LOCAL FISHERMEN REPORT UNUSUAL VESSEL TRAFFIC NEAR RESTRICTED WATERS",
	"ISLAND RESORT RESUMES OPERATIONS UNDER UNKNOWN MANAGEMENT",
	"INTELLIGENCE SOURCES: KNOWN LOCATION ACTIVE AGAIN",
	"ANONYMOUS BENEFACTOR BEHIND REVIVED ISLAND ESTATE, SOURCES SAY",
	"UNDISCLOSED INVESTORS REPORTEDLY FUND RAPID ISLAND RECONSTRUCTION",
	"ISLAND UNDER NEW MANAGEMENT: STAFF SWORN TO SECRECY FROM DAY ONE",
	"MARITIME AGENCY FLAGS UNREGISTERED VESSELS DOCKED AT PRIVATE ISLAND",
]

# Act 3 headlines — breaking news, federal investigation
const ACT3_HEADLINES: Array[String] = [
	"BREAKING: FEDERAL INVESTIGATION OPENED INTO ISLAND OPERATION",
	"SOURCES: ISLAND ACTIVITIES UNDER SCRUTINY BY MULTIPLE AGENCIES",
	"DOJ PROBE: HIGH-PROFILE NAMES SOUGHT IN CONNECTION WITH ISLAND COMPOUND",
	"BREAKING: FORMER GUESTS SUBPOENAED AS INVESTIGATION WIDENS",
	"FBI SEIZES FLIGHT LOGS FROM PRIVATE AIRCRAFT LINKED TO ISLAND HOST",
	"SOURCES: FEDERAL AGENTS HAVE REVIEWED YEARS OF UNDISCLOSED GUEST RECORDS",
	"BREAKING: ISLAND HOST FACES INQUIRY INTO 'PRIVATE ARRANGEMENTS' WITH OFFICIALS",
	"SENATE HEARING CALLED FOLLOWING ISLAND COMPOUND REVELATIONS",
	"FORMER STAFF COOPERATING WITH INVESTIGATORS, SOURCES SAY",
	"BREAKING: ASSETS FROZEN AS AUTHORITIES MOVE AGAINST ISLAND OPERATION",
]

@onready var ticker_label: Label = /TickerLabel

var _current_index: int = 0
var _scroll_x: float = 0.0
var _speed: float = 80.0  # pixels per second
var _current_act: int = 1

const ACT2_THRESHOLD: float = 1000000.0   # M
const ACT3_THRESHOLD: float = 50000000.0  # 0M

func _ready() -> void:
	GameState.lifetime_money_changed.connect(_on_lifetime_money_changed)
	_current_act = _act_for(GameState.lifetime_money)
	var pool := _current_pool()
	_current_index = randi() % pool.size()
	ticker_label.text = "  ★  " + pool[_current_index] + "  ★  " + pool[(_current_index + 1) % pool.size()]
	_scroll_x = 0.0
	# Ghost mode uses sinister Act 1 pool — reassign after initial setup
	if GameState.ghost_mode and _current_act == 1:
		_current_index = randi() % ACT1_GHOST_HEADLINES.size()

func _process(delta: float) -> void:
	_scroll_x -= _speed * delta
	ticker_label.position.x = _scroll_x
	# When the first headline has fully scrolled off, advance and reset
	if _scroll_x < -ticker_label.size.x * 0.5:
		var pool := _current_pool()
		_current_index = (_current_index + 1) % pool.size()
		ticker_label.text = "  ★  " + pool[_current_index] + "  ★  " + pool[(_current_index + 1) % pool.size()]
		_scroll_x = 0.0

func _on_lifetime_money_changed(amount: float) -> void:
	var new_act := _act_for(amount)
	if new_act != _current_act:
		_current_act = new_act
		# Reset index into the new pool; mid-scroll is fine — next cycle will pick up
		_current_index = randi() % _current_pool().size()

func _act_for(amount: float) -> int:
	if amount >= ACT3_THRESHOLD:
		return 3
	elif amount >= ACT2_THRESHOLD:
		return 2
	return 1

func _current_pool() -> Array[String]:
	match _current_act:
		2:
			return ACT2_HEADLINES
		3:
			return ACT3_HEADLINES
		_:
			if GameState.ghost_mode:
				return ACT1_GHOST_HEADLINES
			return ACT1_HEADLINES
